# Generated by Django 3.2.5 on 2021-10-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attedance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attedance',
            name='time',
            field=models.IntegerField(),
        ),
    ]
