# Generated by Django 3.2.5 on 2021-10-07 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attedance_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='attedance',
            new_name='Att',
        ),
    ]
