# Generated by Django 3.2.5 on 2021-10-26 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_mark_attendance4'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mark_attendance4',
            unique_together=set(),
        ),
    ]
